import { describe, it, expect } from 'vitest';
import { parseHardwareRecipeClientSide } from '../../js/io/hardware_profile_sources.js';
import touchAreaPlugin from '../../features/touch_area/plugin.js';
import geekMagicMiniYaml from '../../hardware/geekmagic-mini-esp8266.yaml?raw';
import geekMagicProYaml from '../../hardware/geekmagic-pro-esp32.yaml?raw';
import guitionP4Yaml from '../../hardware/guition-esp32-p4-jc4880p443.yaml?raw';
import guitionP4LargeYaml from '../../hardware/guition-esp32-p4-jc8012p4a1c.yaml?raw';
import elecrowP4Yaml from '../../hardware/elecrow-esp32-p4-9inch-v1.2.yaml?raw';
import reterminalD1001Yaml from '../../hardware/seeedstudio-reterminal-d1001.yaml?raw';
import reterminalStickyYaml from '../../hardware/seeedstudio-reterminal-sticky.yaml?raw';
import m5stackTab5Yaml from '../../hardware/m5stack-tab5.yaml?raw';
import sunton2432s028Yaml from '../../hardware/sunton-esp32-2432s028.yaml?raw';
import sunton2432s028RYaml from '../../hardware/sunton-esp32-2432s028R.yaml?raw';
import waveshareRound128Yaml from '../../hardware/waveshare-esp32-s3-touch-round-lcd-1.28.yaml?raw';
import elecrow7inchYaml from '../../hardware/elecrow-esp32-7inch.yaml?raw';
import guitionJc8048w550Yaml from '../../hardware/guition-esp32-jc8048w550.yaml?raw';
import sunton4827s032RYaml from '../../hardware/sunton-esp32-4827s032R.yaml?raw';
import sunton8048s050Yaml from '../../hardware/sunton-esp32-8048s050.yaml?raw';
import sunton8048s070Yaml from '../../hardware/sunton-esp32-8048s070.yaml?raw';
import waveshare43Yaml from '../../hardware/waveshare-esp32-s3-touch-lcd-4.3.yaml?raw';
import lilygoTdisplayS3Yaml from '../../hardware/lilygo-tdisplays3.yaml?raw';
import waveshare7Yaml from '../../hardware/waveshare-esp32-s3-touch-lcd-7.yaml?raw';
import sensecapIndicatorYaml from '../../hardware/seeedstudio-sensecap-indicator.yaml?raw';

describe('hardware_profile_sources', () => {
    it('parses the ViewDisplay round TFT knob recipe metadata and features', () => {
        const yaml = `
# Name: ViewDisplay ESP32 Round TFT Knob 2.1" UEDX48480021-MD80ET
# Resolution: 480x480
# Shape: round

esp32:
  board: esp32-s3-devkitc-1

psram:
  mode: octal
  speed: 80MHz

display:
  - platform: st7701s
    id: my_display
    dimensions:
      width: 480
      height: 480
    # __LAMBDA_PLACEHOLDER__

touchscreen:
  - platform: cst816
    id: my_touchscreen
`;

        const profile = parseHardwareRecipeClientSide(yaml, 'viewdisplay-esp32-s3-uedx48480021.yaml');

        expect(profile.name).toBe('ViewDisplay ESP32 Round TFT Knob 2.1" UEDX48480021-MD80ET');
        expect(profile.shape).toBe('round');
        expect(profile.resolution).toEqual({ width: 480, height: 480 });
        expect(profile.board).toBe('esp32-s3-devkitc-1');
        expect(profile.displayPlatform).toBe('st7701s');
        expect(profile.features.psram).toBe(true);
        expect(profile.features.lcd).toBe(true);
        expect(profile.features.touch).toBe(true);
        expect(profile.touch).toEqual({ platform: 'cst816', id: 'my_touchscreen' });
        expect(profile.features.epaper).toBe(false);
        expect(profile.hardwarePackage).toBeUndefined();
    });

    it('detects ESP32-P4 boards from esp32 variants and board ids', () => {
        const yaml = `
# Name: Waveshare ESP32-P4 Panel
# Resolution: 800x480
# Shape: rect

esp32:
  board: esp32-p4-evboard
  variant: esp32p4

display:
  - platform: ili9xxx
    id: my_display
`;

        const profile = parseHardwareRecipeClientSide(yaml, 'waveshare-esp32-p4.yaml');

        expect(profile.chip).toBe('esp32-p4');
        expect(profile.board).toBe('esp32-p4-evboard');
        expect(profile.displayPlatform).toBe('ili9xxx');
    });

    it('detects RP2 board variants and recognizes IT8951 as e-paper', () => {
        const rp2Profile = parseHardwareRecipeClientSide(`
# Name: Pico 2 W Paper
# Resolution: 250x122
rp2:
  board: rpipico2w
display:
  - platform: waveshare_epaper
    model: 2.13inv3
`, 'pico-2-w-paper.yaml');
        const e1003Profile = parseHardwareRecipeClientSide(`
# Name: reTerminal E1003
# Resolution: 1872x1404
esp32:
  board: esp32-s3-devkitc-1
display:
  - platform: it8951
    model: Seeed-reTerminal-E1003
`, 'reterminal-e1003.yaml');

        expect(rp2Profile.chip).toBe('rp2350');
        expect(rp2Profile.board).toBe('rpipico2w');
        expect(rp2Profile.features.epaper).toBe(true);
        expect(e1003Profile.displayPlatform).toBe('it8951');
        expect(e1003Profile.features.epaper).toBe(true);
        expect(e1003Profile.features.lcd).toBe(false);
    });

    it('parses the GeekMagic Mini ESP8266 bundled recipe', () => {
        expect(geekMagicMiniYaml).toContain('# ESPHome YAML - Generated by ESPHome Designer');
        expect(geekMagicMiniYaml).toContain('# SETUP INSTRUCTIONS:');
        expect(geekMagicMiniYaml).toContain('# CAPTIVE PORTAL:');

        const profile = parseHardwareRecipeClientSide(geekMagicMiniYaml, 'geekmagic-mini-esp8266.yaml');

        expect(profile.name).toBe('GeekMagic Mini (ESP8266)');
        expect(profile.resolution).toEqual({ width: 240, height: 240 });
        expect(profile.chip).toBe('esp8266');
        expect(profile.board).toBe('esp01_1m');
        expect(profile.displayPlatform).toBe('mipi_spi');
        expect(profile.displayModel).toBe('ST7789V');
        expect(profile.updateInterval).toBe('60s');
        expect(profile.invertColors).toBe(true);
        expect(profile.features.touch).toBe(false);
    });

    it('parses the GeekMagic Pro ESP32 recipe with its required MIPI-SPI settings', () => {
        expect(geekMagicProYaml).toContain('spi_id: spihwd');
        expect(geekMagicProYaml).toContain('data_rate: 40MHz');
        expect(geekMagicProYaml).toContain('spi_mode: MODE3');
        expect(geekMagicProYaml).toContain('invert_colors: true');
        expect(geekMagicProYaml).toContain('auto_clear_enabled: false');

        const profile = parseHardwareRecipeClientSide(geekMagicProYaml, 'geekmagic-pro-esp32.yaml');

        expect(profile.name).toBe('GeekMagic Pro (ESP32)');
        expect(profile.resolution).toEqual({ width: 240, height: 240 });
        expect(profile.board).toBe('esp32dev');
        expect(profile.displayPlatform).toBe('mipi_spi');
        expect(profile.displayModel).toBe('st7789v');
        expect(profile.invertColors).toBe(true);
    });

    it('parses the M5Stack Tab5 bundled recipe', () => {
        expect(m5stackTab5Yaml).toContain('# ESPHome YAML - Generated by ESPHome Designer');
        expect(m5stackTab5Yaml).toContain('# SETUP INSTRUCTIONS:');
        expect(m5stackTab5Yaml).toContain('# CAPTIVE PORTAL:');

        const profile = parseHardwareRecipeClientSide(m5stackTab5Yaml, 'm5stack-tab5.yaml');

        expect(profile.name).toBe('M5Stack Tab5');
        expect(profile.resolution).toEqual({ width: 1280, height: 720 });
        expect(profile.chip).toBe('esp32-p4');
        expect(profile.board).toBe('esp32-p4-evboard');
        expect(profile.displayPlatform).toBe('mipi_dsi');
        expect(profile.displayModel).toBe('M5STACK-TAB5-V2');
        expect(profile.features.psram).toBe(true);
        expect(profile.features.touch).toBe(true);
        expect(profile.features.lcd).toBe(true);
    });

    it('parses the Guition JC4880P443 bundled recipe with required ESP32-P4 support blocks', () => {
        expect(guitionP4Yaml).toContain('esp_ldo:');
        expect(guitionP4Yaml).toContain('esp32_hosted:');
        expect(guitionP4Yaml).toContain('mode: hex');
        expect(guitionP4Yaml).toContain('speed: 200MHz');
        expect(guitionP4Yaml).toContain('pin: GPIO23');
        expect(guitionP4Yaml).toContain('id: main_display');
        expect(guitionP4Yaml).toContain('reset_pin: GPIO27');
        expect(guitionP4Yaml).toContain('id: device_touchscreen');
        expect(guitionP4Yaml).toContain('audio_dac:');

        const profile = parseHardwareRecipeClientSide(guitionP4Yaml, 'guition-esp32-p4-jc4880p443.yaml');

        expect(profile.name).toBe('Guition ESP32-P4 JC4880P443');
        expect(profile.resolution).toEqual({ width: 480, height: 800 });
        expect(profile.chip).toBe('esp32-p4');
        expect(profile.board).toBe('esp32-p4-evboard');
        expect(profile.displayPlatform).toBe('mipi_dsi');
        expect(profile.displayModel).toBe('JC4880P443');
        expect(profile.features.psram).toBe(true);
        expect(profile.features.touch).toBe(true);
        expect(profile.features.lcd).toBe(true);
    });

    it('parses the Guition JC8012P4A1C bundled recipe with required ESP32-P4 support blocks', () => {
        expect(guitionP4LargeYaml).toContain('esp_ldo:');
        expect(guitionP4LargeYaml).toContain('esp32_hosted:');
        expect(guitionP4LargeYaml).toContain('mode: hex');
        expect(guitionP4LargeYaml).toContain('speed: 200MHz');
        expect(guitionP4LargeYaml).toContain('model: JC8012P4A1');
        expect(guitionP4LargeYaml).toContain('rotation: 90');
        expect(guitionP4LargeYaml).toContain('id: main_display');
        expect(guitionP4LargeYaml).toContain('id: device_touchscreen');
        expect(guitionP4LargeYaml).toContain('audio_dac:');

        const profile = parseHardwareRecipeClientSide(guitionP4LargeYaml, 'guition-esp32-p4-jc8012p4a1c.yaml');

        expect(profile.name).toBe('Guition ESP32-P4 JC8012P4A1C');
        expect(profile.resolution).toEqual({ width: 800, height: 1280 });
        expect(profile.chip).toBe('esp32-p4');
        expect(profile.board).toBe('esp32-p4-evboard');
        expect(profile.displayPlatform).toBe('mipi_dsi');
        expect(profile.displayModel).toBe('JC8012P4A1');
        expect(profile.features.psram).toBe(true);
        expect(profile.features.touch).toBe(true);
        expect(profile.features.lcd).toBe(true);
    });

    it('parses the reTerminal D1001 bundled recipe with its XL9535 and GSL3670 wiring', () => {
        expect(reterminalD1001Yaml).toContain('esp_ldo:');
        expect(reterminalD1001Yaml).toContain('esp32_hosted:');
        expect(reterminalD1001Yaml).toContain('mode: hex');
        expect(reterminalD1001Yaml).toContain('flash_size: 32MB');
        expect(reterminalD1001Yaml).toContain('xl9535:');
        expect(reterminalD1001Yaml).toContain('platform: gsl3670');
        expect(reterminalD1001Yaml).toContain('model: SEEED-RETERMINAL-D1001');
        expect(reterminalD1001Yaml).toContain('pin: GPIO14');
        expect(reterminalD1001Yaml).toContain('id: main_display');
        expect(reterminalD1001Yaml).toContain('id: device_touchscreen');
        expect(reterminalD1001Yaml).toContain('audio_dac:');
        expect(reterminalD1001Yaml).toContain('audio_adc:');

        const profile = parseHardwareRecipeClientSide(reterminalD1001Yaml, 'seeedstudio-reterminal-d1001.yaml');

        expect(profile.name).toBe('Seeed Studio reTerminal D1001');
        expect(profile.resolution).toEqual({ width: 800, height: 1280 });
        expect(profile.chip).toBe('esp32-p4');
        expect(profile.board).toBe('esp32-p4-evboard');
        expect(profile.displayPlatform).toBe('mipi_dsi');
        expect(profile.displayModel).toBe('SEEED-RETERMINAL-D1001');
        expect(profile.features.psram).toBe(true);
        expect(profile.features.touch).toBe(true);
        expect(profile.features.lcd).toBe(true);
    });

    it('parses the Elecrow 9-inch V1.2 recipe with its required P4 and C6 wiring', () => {
        expect(elecrowP4Yaml).toContain('variant: esp32c6');
        expect(elecrowP4Yaml).toContain('reset_pin: GPIO32');
        expect(elecrowP4Yaml).toContain('model: WAVESHARE-ESP32-P4-WIFI6-TOUCH-LCD-7B');
        expect(elecrowP4Yaml).toContain('pin: GPIO31');
        expect(elecrowP4Yaml).toContain('pin: GPIO29');

        const profile = parseHardwareRecipeClientSide(elecrowP4Yaml, 'elecrow-esp32-p4-9inch-v1.2.yaml');

        expect(profile.name).toBe('Elecrow ESP32-P4 9" HMI 1024x600 (V1.2)');
        expect(profile.resolution).toEqual({ width: 1024, height: 600 });
        expect(profile.chip).toBe('esp32-p4');
        expect(profile.board).toBe('esp32-p4-evboard');
        expect(profile.displayPlatform).toBe('mipi_dsi');
        expect(profile.features.psram).toBe(true);
        expect(profile.features.touch).toBe(true);
    });

    it('keeps Sunton 2432S028 package dimensions aligned with the landscape transform', () => {
        for (const yaml of [sunton2432s028Yaml, sunton2432s028RYaml]) {
            expect(yaml).toContain('swap_xy: true');
            expect(yaml).toContain(`dimensions:
      height: 240
      width: 320`);
        }
    });

    it('parses the Seeed Studio reTerminal Sticky bundled recipe', () => {
        expect(reterminalStickyYaml).toContain('model: seeed-reterminal-sticky');
        expect(reterminalStickyYaml).toContain('platform: epaper_spi');
        expect(reterminalStickyYaml).toContain('platform: gt911');
        expect(reterminalStickyYaml).toContain('pin: GPIO45');
        expect(reterminalStickyYaml).toContain('pin: GPIO46');

        const profile = parseHardwareRecipeClientSide(reterminalStickyYaml, 'seeedstudio-reterminal-sticky.yaml');

        expect(profile.name).toBe('Seeed Studio reTerminal Sticky');
        expect(profile.resolution).toEqual({ width: 800, height: 480 });
        expect(profile.chip).toBe('esp32-s3');
        expect(profile.board).toBe('esp32-s3-devkitc-1');
        expect(profile.displayPlatform).toBe('epaper_spi');
        expect(profile.displayModel).toBe('seeed-reterminal-sticky');
        expect(profile.features.psram).toBe(true);
        expect(profile.features.touch).toBe(true);
        expect(profile.features.epaper).toBe(true);
        expect(profile.features.lcd).toBe(false);
        expect(profile.touch).toEqual({
            platform: 'gt911',
            id: 'device_touchscreen',
            i2c_id: 'i2c_touch',
            interrupt_pin: 'GPIO21',
            reset_pin: 'GPIO41'
        });
    });

    it('populates profile.touch for custom hardware recipes and enables touch_area export (Issue #502)', () => {
        const customYaml = `
# Name: LILYGO T5 4.7
# Resolution: 960x540
display:
  - platform: t547
    id: epaper_display
touchscreen:
  - platform: gt911
    id: my_touchscreen
    i2c_id: bus_a
    interrupt_pin: GPIO47
`;
        const profile = parseHardwareRecipeClientSide(customYaml, 'lilygo-t5.yaml');
        expect(profile.features.touch).toBe(true);
        expect(profile.touch).toEqual({
            platform: 'gt911',
            id: 'my_touchscreen',
            i2c_id: 'bus_a',
            interrupt_pin: 'GPIO47'
        });

        const exportContext = {
            lines: [],
            widgets: [
                {
                    id: 'touch_1',
                    type: 'touch_area',
                    x: 10,
                    y: 20,
                    width: 50,
                    height: 50,
                    props: { nav_action: 'next_page' }
                },
                {
                    id: 'touch_2',
                    type: 'touch_area',
                    _pageIndex: 1,
                    x: 10,
                    y: 20,
                    width: 50,
                    height: 50,
                    props: { nav_action: 'previous_page' }
                }
            ],
            profile
        };
        touchAreaPlugin.onExportBinarySensors(exportContext);
        expect(exportContext.lines.length).toBeGreaterThan(0);
        expect(exportContext.lines).toContain('- platform: touchscreen');
        expect(exportContext.lines).toContain('  touchscreen_id: my_touchscreen');
    });

        it('parses the Waveshare Touch Round LCD 1.28 bundled recipe', () => {

        expect(waveshareRound128Yaml).toContain('model: GC9A01A');
        expect(waveshareRound128Yaml).toContain('platform: ili9xxx');
        expect(waveshareRound128Yaml).toContain('platform: cst816');

        const profile = parseHardwareRecipeClientSide(waveshareRound128Yaml, 'waveshare-esp32-s3-touch-round-lcd-1.28.yaml');

        expect(profile.name).toBe('Waveshare Touch Round LCD 1.28"');
        expect(profile.resolution).toEqual({ width: 240, height: 240 });
        expect(profile.shape).toBe('round');
        expect(profile.chip).toBe('esp32-s3');
        expect(profile.board).toBe('waveshare_esp32s3_touch_lcd_128');
        expect(profile.displayPlatform).toBe('ili9xxx');
        expect(profile.displayModel).toBe('GC9A01A');
        expect(profile.features.psram).toBe(true);
        expect(profile.features.touch).toBe(true);
        expect(profile.features.lcd).toBe(true);
        expect(profile.touch).toEqual({
            platform: 'cst816',
            id: 'my_touchscreen',
            interrupt_pin: '$tpintpin',
            reset_pin: '$tprstpin'
        });
    });

    it('declares the RPI model with verified timings on the Elecrow 7 inch recipe (Issue #520)', () => {
        expect(elecrow7inchYaml).toContain('platform: mipi_rgb');
        expect(elecrow7inchYaml).toContain('model: RPI');
        expect(elecrow7inchYaml).toContain('invert_colors: true');
        expect(elecrow7inchYaml).toContain('pclk_frequency: 15MHz');

        const profile = parseHardwareRecipeClientSide(elecrow7inchYaml, 'elecrow-esp32-7inch.yaml');

        expect(profile.displayPlatform).toBe('mipi_rgb');
        expect(profile.displayModel).toBe('RPI');
    });

    it('declares a model on every bundled mipi_rgb display block (Issue #520)', () => {
        const recipes = {
            'elecrow-esp32-7inch.yaml': elecrow7inchYaml,
            'guition-esp32-jc8048w550.yaml': guitionJc8048w550Yaml,
            'sunton-esp32-4827s032R.yaml': sunton4827s032RYaml,
            'sunton-esp32-8048s050.yaml': sunton8048s050Yaml,
            'sunton-esp32-8048s070.yaml': sunton8048s070Yaml,
            'waveshare-esp32-s3-touch-lcd-4.3.yaml': waveshare43Yaml,
            'waveshare-esp32-s3-touch-lcd-7.yaml': waveshare7Yaml,
            'seeedstudio-sensecap-indicator.yaml': sensecapIndicatorYaml
        };

        for (const [filename, yaml] of Object.entries(recipes)) {
            expect(yaml).toContain('platform: mipi_rgb');
            const block = yaml.slice(yaml.indexOf('platform: mipi_rgb'));
            const entry = block.slice(0, block.indexOf('# __LAMBDA_PLACEHOLDER__') === -1
                ? 2500
                : block.indexOf('# __LAMBDA_PLACEHOLDER__'));
            expect(`${filename} must declare model: for mipi_rgb; got: ${entry.slice(0, 120)}`).toContain('model:');
        }

        expect(waveshare43Yaml).toContain('model: ESP32-S3-TOUCH-LCD-4.3');
        expect(waveshare7Yaml).toContain('model: ESP32-S3-TOUCH-LCD-7-800X480');
        expect(sensecapIndicatorYaml).toContain('model: SEEED-INDICATOR-D1');
    });

    it('drives the LilyGo T-Display S3 via mipi_spi without the removed ili9xxx i80 bus (Issue #535)', () => {
        expect(lilygoTdisplayS3Yaml).toContain('platform: mipi_spi');
        expect(lilygoTdisplayS3Yaml).toContain('model: t-display-s3');
        expect(lilygoTdisplayS3Yaml).toContain('type: octal');
        expect(lilygoTdisplayS3Yaml).not.toContain('bus_type:');
        expect(lilygoTdisplayS3Yaml).not.toMatch(/^\s*i80:\s*$/m);
        expect(lilygoTdisplayS3Yaml).toContain('rotation: 270');
        expect(lilygoTdisplayS3Yaml).toContain('# __LAMBDA_PLACEHOLDER__');
    });

    it('powers the M5Stack Tab5 MIPI DSI PHY via esp_ldo (Issue #535)', () => {
        expect(m5stackTab5Yaml).toContain('esp_ldo:');
        expect(m5stackTab5Yaml).toContain('channel: 3');
        expect(m5stackTab5Yaml).toContain('voltage: 2.5V');
        expect(m5stackTab5Yaml).toContain('model: M5STACK-TAB5-V2');
    });

    it('keeps on_release at touchscreen entry level in every hardware recipe (Issue #539)', async () => {
        const fs = await import('node:fs');
        const path = await import('node:path');
        const { fileURLToPath } = await import('node:url');
        const hardwareDir = path.join(
            path.dirname(fileURLToPath(import.meta.url)),
            '../../hardware'
        );
        const entryKeys = [
            'platform', 'id', 'display', 'i2c_id', 'spi_id', 'address',
            'update_interval', 'interrupt_pin', 'reset_pin', 'cs_pin',
            'transform', 'calibration', 'model', 'on_release', 'on_touch',
            'setup_priority'
        ];
        const files = fs.readdirSync(hardwareDir).filter((file) => file.endsWith('.yaml'));
        expect(files.length).toBeGreaterThan(0);

        for (const file of files) {
            const lines = fs.readFileSync(path.join(hardwareDir, file), 'utf8').split('\n');
            const start = lines.findIndex((line) => line.trim() === 'touchscreen:');
            if (start === -1) continue;
            let end = lines.length;
            for (let i = start + 1; i < lines.length; i++) {
                if (/^\S/.test(lines[i]) && lines[i].trim() !== '' && !lines[i].startsWith('#')) {
                    end = i;
                    break;
                }
            }
            const section = lines.slice(start, end);
            section.forEach((line, index) => {
                const match = line.match(/^(\s*)on_release:\s*$/);
                if (!match) return;
                const keyPattern = new RegExp(`^ {${match[1].length}}(${entryKeys.join('|')}):`);
                const hasSibling = section.some((other, otherIndex) => otherIndex !== index && keyPattern.test(other));
                expect(
                    hasSibling,
                    `${file}:${start + index + 1} nests on_release under transform`
                ).toBe(true);
            });
        }
    });
});
